apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: web-partner-secret
  namespace: platform
spec:
  encryptedData:
    AUTH_SECRET: REPLACE_WITH_SEALED_VALUE
    AUTH_GOOGLE_ID: REPLACE_WITH_SEALED_VALUE
    AUTH_GOOGLE_SECRET: REPLACE_WITH_SEALED_VALUE
    DATABASE_URL: REPLACE_WITH_SEALED_VALUE
  template:
    metadata:
      name: web-partner-secret
      namespace: platform
    type: Opaque
