replicaCount: 1
image:
  tag: sha-b76bc40
ingress:
  enabled: true
  host: admin.staging.example.com
  tls:
    enabled: true
    clusterIssuer: letsencrypt-staging
env:
  NODE_ENV: production
  NEXTAUTH_URL: https://admin.staging.example.com
