replicaCount: 1
image:
  tag: sha-e363d53
ingress:
  enabled: true
  host: partner.staging.example.com
  tls:
    enabled: true
    clusterIssuer: letsencrypt-staging
env:
  NODE_ENV: production
  NEXTAUTH_URL: https://partner.staging.example.com
